service: csv-update-post #Name of your App

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x # Node JS version
  memorySize: 512
  timeout: 15
  stage: production
  region: us-east-1 # AWS region

functions:
  update-post:
    handler: lambda.handler
    events:
      - schedule:
          rate: cron(0 0 ? * SUN *)
          enabled: true
